version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  pulse:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: pulse
    ports:
      - "8000:8000"

volumes:
  grafana-data:
